services:
  hyperf-pix:
    container_name: hyperf-pix
    image: hyperf-pix
    build:
      context: .
    volumes:
      - ./:/opt/www
    ports:
      - 9501:9501
    environment:
      - APP_ENV=dev
      - SCAN_CACHEABLE=false

networks:
  default:
    name: hyperf-pix
